/*******************************************************
* Fixed.frag Fixed Function Equivalent Fragment Shader *
*   Automatically Generated by 3Dlabs GLSL ShaderGen   *
*             http://developer.3dlabs.com              *
*******************************************************/

void main (void) 
{
    vec4 color;

    color = gl_Color;

    color += gl_SecondaryColor;
    color = clamp(color, 0.0, 1.0);

    gl_FragColor = color;
}
